import { and, eq, gt, isNull } from "drizzle-orm";
import type { PostgresJsDatabase } from "drizzle-orm/postgres-js";
import type { AuthRepository } from "../auth/service.ts";
import { createMemoryKey } from "../auth/memory-identity.ts";
import { agents, emailVerifications, memoryIdentities, userSessions, users } from "./schema.ts";
import * as schema from "./schema.ts";
type Database=PostgresJsDatabase<typeof schema>;
export function createDrizzleAuthRepository(db:Database):AuthRepository{return{
 async saveVerification(input){await db.insert(emailVerifications).values(input)},
 async consumeVerification(tokenHash){return db.transaction(async tx=>{const rows=await tx.update(emailVerifications).set({consumedAt:new Date()}).where(and(eq(emailVerifications.tokenHash,tokenHash),isNull(emailVerifications.consumedAt),gt(emailVerifications.expiresAt,new Date()))).returning({email:emailVerifications.email,expiresAt:emailVerifications.expiresAt});return rows[0]??null})},
 async provisionAccount(input){return db.transaction(async tx=>{const existing=await tx.select({id:users.id}).from(users).where(eq(users.email,input.email)).limit(1);const userId=existing[0]?.id??(await tx.insert(users).values({email:input.email}).returning({id:users.id}))[0]!.id;const memories=await tx.select({memoryKey:memoryIdentities.memoryKey}).from(memoryIdentities).where(eq(memoryIdentities.userId,userId)).limit(1);if(!memories[0])await tx.insert(memoryIdentities).values({userId,memoryKey:createMemoryKey()});const current=await tx.select({id:agents.id}).from(agents).where(eq(agents.userId,userId)).limit(1);const agentId=current[0]?.id??(await tx.insert(agents).values({userId,name:input.agent.name,riskProfile:"balanced",tradingStyle:"general onchain assistant",approvalMode:input.agent.autonomyMode==="manual"?"approve":"autonomous",autonomyMode:input.agent.autonomyMode,budgetUsd:String(input.agent.budgetUsd),dailyCapUsd:String(input.agent.dailyCapUsd),perTradeCapUsd:String(input.agent.perTradeCapUsd),maxSlippageBps:input.agent.maxSlippageBps,allowedChains:[...input.agent.allowedChains],allowedTokens:[...input.agent.allowedTokens]}).returning({id:agents.id}))[0]!.id;await tx.insert(userSessions).values({userId,tokenHash:input.sessionTokenHash,expiresAt:input.sessionExpiresAt});return{userId,agentId}})}
}}
export async function resolveSession(db:Database,tokenHash:string){const rows=await db.select({userId:userSessions.userId,email:users.email,agentId:agents.id,agentName:agents.name,autonomyMode:agents.autonomyMode,memoryKey:memoryIdentities.memoryKey,khOrgId:agents.khOrgId,khWalletAddress:agents.khWalletAddress,khHmacSecretEncrypted:agents.khHmacSecretEncrypted}).from(userSessions).innerJoin(users,eq(users.id,userSessions.userId)).innerJoin(agents,eq(agents.userId,users.id)).innerJoin(memoryIdentities,eq(memoryIdentities.userId,users.id)).where(and(eq(userSessions.tokenHash,tokenHash),gt(userSessions.expiresAt,new Date()))).limit(1);return rows[0]??null;}
