import assert from "node:assert/strict";
import test from "node:test";
import { handleApprovalRequest } from "../lib/chat/approval-api.ts";
import { createChatPipeline } from "../lib/chat/pipeline.ts";
const pipeline = createChatPipeline({ mode: "mock", chains: { base: "8453" }, tokens: { ETH: "0x1111111111111111111111111111111111111111", USDC: "0x2222222222222222222222222222222222222222" }, router: "0x3333333333333333333333333333333333333333" });
test("approval API is disabled unless every mock execution gate is configured", async () => { assert.deepEqual(await handleApprovalRequest({}, { enabled: false, pipeline, async execute() { throw new Error("must not run"); } }), { status: 503, body: { error: "mock_approval_unavailable" } }); });
test("approval API reconstructs the bounded preview before execution", async () => { let calls=0; const response=await handleApprovalRequest({ text:"swap 0.001 ETH to USDC on base",correlationId:"approval-api-1",recalledMemory:["Use Base only."]},{enabled:true,pipeline,async execute(preview,memory){calls++;assert.equal(preview.request.chainId,"8453");assert.deepEqual(memory,["Use Base only."]);return{kind:"executed",audit:{id:"audit-1",status:"confirmed",transactionHash:"0xabc"}};}}); assert.equal(response.status,200); assert.equal(calls,1); });
test("approval API refuses unsupported mock pairs before execution", async () => { let calls=0; const response=await handleApprovalRequest({ text:"swap 1 USDC to ETH on base",correlationId:"approval-api-2"},{enabled:true,pipeline,async execute(){calls++;return{kind:"executed",audit:{id:"must-not-run",status:"confirmed"}};}}); assert.deepEqual(response,{status:409,body:{error:"unsupported_mock_trade",reason:"Only the captured 0.001 ETH to USDC trade on Base can be approved in mock mode."}}); assert.equal(calls,0); });
test("approval API refuses unsupported mock amounts before execution", async () => { let calls=0; const response=await handleApprovalRequest({ text:"swap 0.002 ETH to USDC on base",correlationId:"approval-api-3"},{enabled:true,pipeline,async execute(){calls++;return{kind:"executed",audit:{id:"must-not-run",status:"confirmed"}};}}); assert.equal(response.status,409); assert.equal(calls,0); });
