import assert from"node:assert/strict";import test from"node:test";import{createMemoryClient}from"../lib/memory/client.ts";
const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}});
test("memory recall distinguishes empty locked truncated and retired states",async()=>{const bodies=[{enabled:true,records:[]},{enabled:true,records:[],locked:true},{enabled:true,records:["one"],truncated:true},{enabled:true,records:[],retired:true}];for(const body of bodies){const client=createMemoryClient({baseUrl:"http://memory",fetcher:async()=>response(body)});const result=await client.recall({user:"u",passphrase:"p",query:"q",folder:"f"});assert.equal(result.kind,body.retired?"retired":body.locked?"locked":body.truncated?"recalled":"empty");if(result.kind==="recalled")assert.equal(result.truncated,true)}});
test("memory outage never throws into the agent",async()=>{const client=createMemoryClient({baseUrl:"http://memory",fetcher:async()=>{throw new Error("offline")}});assert.deepEqual(await client.recall({user:"u",passphrase:"p",query:"q"}),{kind:"unreachable"})});
test("remember preserves durable local receipts",async()=>{const client=createMemoryClient({baseUrl:"http://memory",fetcher:async()=>response({ok:true,enabled:true,local:true,blob_id:"local:abc"})});assert.deepEqual(await client.remember({user:"u",passphrase:"p",text:"decision"}),{kind:"stored",receipt:"local:abc",local:true})});
test("forget confirms that a memory folder is no longer served",async()=>{const client=createMemoryClient({baseUrl:"http://memory",fetcher:async(input,init)=>{assert.equal(String(input),"http://memory/forget");assert.deepEqual(JSON.parse(String(init?.body)),{user:"u",passphrase:"p",folder:"project-x"});return response({forgotten:true,enabled:true})}});assert.deepEqual(await client.forget({user:"u",passphrase:"p",folder:"project-x"}),{kind:"forgotten"})});
test("memory status exposes bounded operational health",async()=>{const client=createMemoryClient({baseUrl:"http://memory/",fetcher:async(input,init)=>{assert.equal(String(input),"http://memory/health");assert.equal(init?.method,"GET");return response({status:"ok",enabled:true,buffered_local:2,cached_local:11,quilts:3,last_flush:"2026-08-07T08:00:00.000Z",next_flush_at:null,last_flush_error:null})}});assert.deepEqual(await client.memoryStatus(),{kind:"available",bufferedLocal:2,cachedLocal:11,quilts:3,lastFlush:"2026-08-07T08:00:00.000Z",nextFlushAt:null,lastFlushError:null})});
test("portable file roundtrip preserves receipts metadata and bytes",async()=>{const replies=[{ok:true,enabled:true,files_enabled:true,blob_id:"walrus:blob",receipt:"local:index"},{enabled:true,files:[{name:"rules.txt",size:5,blobId:"walrus:blob",contentType:"text/plain",ts:123,available:true}],expired:0},{ok:true,dataBase64:"aGVsbG8="}];const paths:string[]=[];const client=createMemoryClient({baseUrl:"http://memory",fetcher:async(input)=>{paths.push(String(input));return response(replies.shift())}});assert.deepEqual(await client.uploadFile({user:"u",passphrase:"p",folder:"f",name:"rules.txt",contentType:"text/plain",dataBase64:"aGVsbG8="}),{kind:"uploaded",blobId:"walrus:blob",receipt:"local:index"});assert.deepEqual(await client.listFiles({user:"u",passphrase:"p",folder:"f"}),{kind:"files",files:[{name:"rules.txt",size:5,blobId:"walrus:blob",contentType:"text/plain",timestamp:123,available:true}],expired:0});assert.deepEqual(await client.downloadFile({user:"u",passphrase:"p",blobId:"walrus:blob"}),{kind:"downloaded",dataBase64:"aGVsbG8="});assert.deepEqual(paths,["http://memory/file/upload","http://memory/file/list","http://memory/file/download"])});

test("memory status accepts the production AgentQA flush receipt",async()=>{const client=createMemoryClient({baseUrl:"http://memory",fetcher:async()=>response({status:"ok",enabled:true,buffered_local:1,cached_local:392,quilts:18,last_flush:{at:"2026-08-10T16:23:33.311Z",blobId:"blob-1",count:12},next_flush_at:"2026-08-10T22:23:33.311Z",last_flush_error:null})});assert.deepEqual(await client.memoryStatus(),{kind:"available",bufferedLocal:1,cachedLocal:392,quilts:18,lastFlush:"2026-08-10T16:23:33.311Z",nextFlushAt:"2026-08-10T22:23:33.311Z",lastFlushError:null})});