export type MemoryResult<T>={readonly kind:"stored";readonly receipt?:string|undefined;readonly local:boolean}|{readonly kind:"recalled";readonly records:readonly string[];readonly truncated:boolean}|{readonly kind:"forgotten"}|{readonly kind:"empty"}|{readonly kind:"locked"}|{readonly kind:"retired"}|{readonly kind:"disabled"}|{readonly kind:"unreachable"}|{readonly kind:"invalid";readonly reason:string};
export type MemoryStatusResult={readonly kind:"available";readonly bufferedLocal:number;readonly cachedLocal:number;readonly quilts:number;readonly lastFlush:string|null;readonly nextFlushAt:string|null;readonly lastFlushError:string|null}|{readonly kind:"disabled"}|{readonly kind:"unreachable"}|{readonly kind:"invalid";readonly reason:string};
export type MemoryFile={readonly name:string;readonly size:number;readonly blobId:string;readonly contentType:string;readonly timestamp:number;readonly available:boolean|null};
type FileFailure={readonly kind:"locked"}|{readonly kind:"retired"}|{readonly kind:"disabled"}|{readonly kind:"unreachable"}|{readonly kind:"expired"}|{readonly kind:"invalid";readonly reason:string};
export type UploadFileResult={readonly kind:"uploaded";readonly blobId:string;readonly receipt?:string|undefined}|FileFailure;
export type ListFilesResult={readonly kind:"files";readonly files:readonly MemoryFile[];readonly expired:number}|FileFailure;
export type DownloadFileResult={readonly kind:"downloaded";readonly dataBase64:string}|FileFailure;
type Fetcher=(input:RequestInfo|URL,init?:RequestInit)=>Promise<Response>;
type Options={readonly baseUrl?:string;readonly fetcher?:Fetcher};
type Identity={readonly user:string;readonly passphrase:string;readonly folder?:string};
type RecallInput=Identity&{readonly query:string;readonly limit?:number};
const json=async(response:Response):Promise<Record<string,unknown>|null>=>{try{const value:unknown=await response.json();return value&&typeof value==="object"?value as Record<string,unknown>:null}catch{return null}};
function state(body:Record<string,unknown>):MemoryResult<never>{if(body.retired===true)return{kind:"retired"};if(body.locked===true)return{kind:"locked"};if(body.enabled!==true)return{kind:"disabled"};return{kind:"empty"}};
export function createMemoryClient(options:Options={}){let base=options.baseUrl??"http://127.0.0.1:4000";while(base.endsWith("/"))base=base.slice(0,-1);const fetcher=options.fetcher??fetch;
  async function recall(input:RecallInput):Promise<MemoryResult<readonly string[]>>{if(!input.user||!input.passphrase||!input.query)return{kind:"invalid",reason:"user, passphrase, and query are required"};try{const response=await fetcher(base+"/recall",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({user:input.user,passphrase:input.passphrase,query:input.query,folder:input.folder??"",limit:input.limit??8})});const body=await json(response);if(!response.ok||!body)return{kind:"unreachable"};const fallback=state(body);if(fallback.kind!=="empty")return fallback;const records=Array.isArray(body.records)?body.records.filter((value):value is string=>typeof value==="string"):[];return records.length?{kind:"recalled",records,truncated:body.truncated===true}:{kind:"empty"}}catch{return{kind:"unreachable"}}}
  async function remember(input:Identity&{readonly text:string}):Promise<MemoryResult<never>>{if(!input.user||!input.passphrase||!input.text)return{kind:"invalid",reason:"user, passphrase, and text are required"};try{const response=await fetcher(base+"/remember",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({user:input.user,passphrase:input.passphrase,text:input.text,folder:input.folder??""})});const body=await json(response);if(!response.ok||!body)return{kind:"unreachable"};if(body.enabled!==true)return{kind:"disabled"};if(body.ok!==true)return{kind:"invalid",reason:"memory write was not confirmed"};return{kind:"stored",receipt:typeof body.blob_id==="string"?body.blob_id:undefined,local:body.local===true}}catch{return{kind:"unreachable"}}}
  async function forget(input:Identity):Promise<MemoryResult<never>>{if(!input.user||!input.passphrase)return{kind:"invalid",reason:"user and passphrase are required"};try{const response=await fetcher(base+"/forget",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({user:input.user,passphrase:input.passphrase,folder:input.folder??""})});const body=await json(response);if(!body)return{kind:"unreachable"};if(response.status===403)return{kind:"locked"};if(!response.ok)return{kind:"unreachable"};if(body.enabled!==true)return{kind:"disabled"};if(body.forgotten===true)return{kind:"forgotten"};if(typeof body.error==="string"&&body.error.toLowerCase().includes("retired"))return{kind:"retired"};return{kind:"invalid",reason:"memory forget was not confirmed"}}catch{return{kind:"unreachable"}}}
  async function memoryStatus():Promise<MemoryStatusResult>{try{const response=await fetcher(base+"/health",{method:"GET"});const body=await json(response);if(!response.ok||!body)return{kind:"unreachable"};if(body.enabled!==true)return{kind:"disabled"};if(body.status!=="ok"||!Number.isInteger(body.buffered_local)||!Number.isInteger(body.cached_local)||!Number.isInteger(body.quilts))return{kind:"invalid",reason:"malformed memory health response"};const nullableString=(value:unknown)=>value===null||typeof value==="string";const flush=body.last_flush;const flushAt=flush===null||typeof flush==="string"?flush:flush&&typeof flush==="object"&&typeof (flush as Record<string,unknown>).at==="string"?(flush as Record<string,unknown>).at as string:undefined;if(flushAt===undefined||!nullableString(body.next_flush_at)||!nullableString(body.last_flush_error))return{kind:"invalid",reason:"malformed memory health response"};return{kind:"available",bufferedLocal:body.buffered_local as number,cachedLocal:body.cached_local as number,quilts:body.quilts as number,lastFlush:flushAt,nextFlushAt:body.next_flush_at as string|null,lastFlushError:body.last_flush_error as string|null}}catch{return{kind:"unreachable"}}}
  async function uploadFile(input:Identity&{readonly name:string;readonly contentType?:string;readonly dataBase64:string}):Promise<UploadFileResult>{if(!input.user||!input.passphrase||!input.name||!input.dataBase64)return{kind:"invalid",reason:"user, passphrase, name, and dataBase64 are required"};try{const response=await fetcher(base+"/file/upload",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({user:input.user,passphrase:input.passphrase,folder:input.folder??"",name:input.name,contentType:input.contentType??"application/octet-stream",dataBase64:input.dataBase64})});const body=await json(response);if(!response.ok||!body)return{kind:"unreachable"};if(body.files_enabled===false||body.enabled===false)return{kind:"disabled"};if(typeof body.error==="string"&&body.error.toLowerCase().includes("retired"))return{kind:"retired"};if(body.ok!==true||typeof body.blob_id!=="string"||!body.blob_id)return{kind:"invalid",reason:"file upload was not confirmed"};return{kind:"uploaded",blobId:body.blob_id,receipt:typeof body.receipt==="string"?body.receipt:undefined}}catch{return{kind:"unreachable"}}}
  async function listFiles(input:Identity):Promise<ListFilesResult>{if(!input.user||!input.passphrase)return{kind:"invalid",reason:"user and passphrase are required"};try{const response=await fetcher(base+"/file/list",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({user:input.user,passphrase:input.passphrase,folder:input.folder??""})});const body=await json(response);if(!response.ok||!body)return{kind:"unreachable"};if(body.enabled!==true)return{kind:"disabled"};if(body.retired===true)return{kind:"retired"};if(body.locked===true)return{kind:"locked"};if(!Array.isArray(body.files)||!Number.isInteger(body.expired))return{kind:"invalid",reason:"malformed file list response"};const files:MemoryFile[]=[];for(const value of body.files){if(!value||typeof value!=="object")return{kind:"invalid",reason:"malformed file record"};const file=value as Record<string,unknown>;if(typeof file.name!=="string"||typeof file.size!=="number"||typeof file.blobId!=="string"||typeof file.contentType!=="string"||typeof file.ts!=="number"||(typeof file.available!=="boolean"&&file.available!==null))return{kind:"invalid",reason:"malformed file record"};files.push({name:file.name,size:file.size,blobId:file.blobId,contentType:file.contentType,timestamp:file.ts,available:file.available})}return{kind:"files",files,expired:body.expired as number}}catch{return{kind:"unreachable"}}}
  async function downloadFile(input:Identity&{readonly blobId:string}):Promise<DownloadFileResult>{if(!input.user||!input.passphrase||!input.blobId)return{kind:"invalid",reason:"user, passphrase, and blobId are required"};try{const response=await fetcher(base+"/file/download",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({user:input.user,passphrase:input.passphrase,blobId:input.blobId})});const body=await json(response);if(!response.ok||!body)return{kind:"unreachable"};if(body.files_enabled===false)return{kind:"disabled"};if(body.locked===true)return{kind:"locked"};if(body.expired===true)return{kind:"expired"};if(typeof body.error==="string"&&body.error.toLowerCase().includes("retired"))return{kind:"retired"};if(body.ok!==true||typeof body.dataBase64!=="string"||!body.dataBase64)return{kind:"invalid",reason:"file download was not confirmed"};return{kind:"downloaded",dataBase64:body.dataBase64}}catch{return{kind:"unreachable"}}}
  return{recall,remember,forget,memoryStatus,uploadFile,listFiles,downloadFile};
}
