import { z } from "zod";
import { AUCTOR_SYSTEM_PROMPT } from "./prompt.ts";

const intent=z.object({intent:z.enum(["greeting","help","cancel","preference","trade","portfolio","task","strategy","memory","notification","unknown"]),amount:z.string().optional(),tokenIn:z.string().optional(),tokenOut:z.string().optional(),chain:z.string().optional(),reply:z.string().max(600).optional()}).strict().superRefine((value,ctx)=>{if(value.intent==="trade"&&(!value.amount||!value.tokenIn||!value.tokenOut||!value.chain))ctx.addIssue({code:"custom",message:"Trade fields are required."})});
export type LlmIntent=z.infer<typeof intent>;
type Context={text:string;memory:readonly string[];agent:{name:string;autonomyMode:string;dailyCapUsd:string}};
type Options={provider:"anthropic"|"openrouter"|"ollama";model:string;apiKey:string|null;fallback?:{baseUrl:string;model:string;apiKey:string}|null;fetch?:typeof globalThis.fetch};
export function createLlmClient(options:Options){const fetcher=options.fetch??fetch;return{async interpret(context:Context):Promise<{kind:"interpreted";value:LlmIntent}|{kind:"unavailable";reason:string}>{if(options.provider!=="ollama"&&!options.apiKey)return{kind:"unavailable",reason:"llm_not_configured"};const primary=await call(fetcher,endpoint(options.provider),options,context);if(primary.kind==="interpreted"||!options.fallback)return primary;return call(fetcher,`${options.fallback.baseUrl}/v1/messages`,{...options,provider:"anthropic",model:options.fallback.model,apiKey:options.fallback.apiKey,fallback:null},context)}}}
async function call(fetcher:typeof globalThis.fetch,url:string,options:Options,context:Context):Promise<{kind:"interpreted";value:LlmIntent}|{kind:"unavailable";reason:string}>{try{const response=await fetcher(url,{...request(options,context),signal:AbortSignal.timeout(20_000)});if(!response.ok)return{kind:"unavailable",reason:"provider_unavailable"};const body:unknown=await response.json();const text=readText(options.provider,body).replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"").trim();const parsed=intent.safeParse(JSON.parse(text));return parsed.success?{kind:"interpreted",value:parsed.data}:{kind:"unavailable",reason:"invalid_llm_response"}}catch{return{kind:"unavailable",reason:"provider_unavailable"}}}
function endpoint(provider:Options["provider"]){if(provider==="anthropic")return"https://api.anthropic.com/v1/messages";if(provider==="openrouter")return"https://openrouter.ai/api/v1/chat/completions";return"http://127.0.0.1:11434/api/chat"}
function request(options:Options,context:Context):RequestInit{const user=JSON.stringify({user_message:context.text,recalled_memory:context.memory,agent:context.agent});if(options.provider==="anthropic")return{method:"POST",headers:{"content-type":"application/json","x-api-key":options.apiKey??"","anthropic-version":"2023-06-01"},body:JSON.stringify({model:options.model,max_tokens:500,temperature:0,system:AUCTOR_SYSTEM_PROMPT,messages:[{role:"user",content:user}]})};return{method:"POST",headers:{"content-type":"application/json",...(options.apiKey?{authorization:`Bearer ${options.apiKey}`}:{})},body:JSON.stringify({model:options.model,temperature:0,stream:false,response_format:{type:"json_object"},messages:[{role:"system",content:AUCTOR_SYSTEM_PROMPT},{role:"user",content:user}]})}}
function readText(provider:Options["provider"],body:unknown):string{if(typeof body!=="object"||body===null)throw new Error("invalid");if(provider==="anthropic"&&"content"in body&&Array.isArray(body.content)){const first=body.content[0];if(typeof first==="object"&&first!==null&&"text"in first&&typeof first.text==="string")return first.text}if("choices"in body&&Array.isArray(body.choices)){const first=body.choices[0];if(typeof first==="object"&&first!==null&&"message"in first&&typeof first.message==="object"&&first.message!==null&&"content"in first.message&&typeof first.message.content==="string")return first.message.content}if("message"in body&&typeof body.message==="object"&&body.message!==null&&"content"in body.message&&typeof body.message.content==="string")return body.message.content;throw new Error("invalid")}
