import type { ExecutionRequest, ExecutionStatus, KeeperHubClient, Simulation } from "../keeperhub/types.ts";
import { evaluatePolicy, type PolicyInput, type PolicyRules, type PolicyVerdict } from "../policy/engine.ts";
import { err, ok, type Result } from "../result.ts";
export type AuditStatus = "pending" | "simulating" | "submitted" | "confirmed" | "failed" | "refused";
export interface ExecutionAudit { readonly id: string; readonly agentId: string; readonly correlationId: string; readonly status: AuditStatus; readonly recalledMemory?: readonly string[]; readonly policyVerdict?: PolicyVerdict; readonly simulation?: Simulation; readonly keeperHubExecutionId?: string; readonly transactionHash?: string; }
export interface ExecutionRepository { find(agentId: string, correlationId: string): Promise<ExecutionAudit | null>; claim(input: { agentId: string; correlationId: string; chainId: string; intent: unknown; recalledMemory?: readonly string[] }): Promise<{ audit: ExecutionAudit; created: boolean }>; recordPolicy(id: string, verdict: PolicyVerdict, status: "simulating" | "refused"): Promise<ExecutionAudit>; recordSimulation(id: string, simulation: Simulation): Promise<ExecutionAudit>; recordSubmission(id: string, keeperHubExecutionId: string): Promise<ExecutionAudit>; recordTerminal(id: string, status: ExecutionStatus): Promise<ExecutionAudit>; recordFailure(id: string, reason: string): Promise<ExecutionAudit>; addSpend(input: { agentId: string; executionId: string; kind: "trade"; amountUsdMicros: bigint; utcDay: string }): Promise<void>; }
export interface ExecuteTradeInput { readonly agentId: string; readonly request: ExecutionRequest; readonly policyInput: PolicyInput; readonly policyRules: PolicyRules; readonly recalledMemory?: readonly string[]; readonly now?: Date; }
export type LifecycleError = { readonly code: "policy_refused" | "keeperhub_failed"; readonly message: string };
export function createExecutionService(deps: { repository: ExecutionRepository; keeperHub: KeeperHubClient }) { return { async executeTrade(input: ExecuteTradeInput): Promise<Result<ExecutionAudit, LifecycleError>> {
  const existing = await deps.repository.find(input.agentId, input.request.correlationId); if (existing) return ok(existing);
  const claim = await deps.repository.claim({ agentId: input.agentId, correlationId: input.request.correlationId, chainId: input.request.chainId, intent: input.request, ...(input.recalledMemory ? { recalledMemory: input.recalledMemory } : {}) }); if (!claim.created) return ok(claim.audit); let audit = claim.audit;
  const verdict = evaluatePolicy(input.policyInput, input.policyRules); audit = await deps.repository.recordPolicy(audit.id, verdict, verdict.allowed ? "simulating" : "refused");
  if (!verdict.allowed) return err({ code: "policy_refused", message: verdict.reasons.map((reason) => reason.code).join(",") });
  const simulation = await deps.keeperHub.simulate(input.request); if (!simulation.ok || simulation.value.wouldRevert) { const message = simulation.ok ? simulation.value.revertReason ?? "Simulation would revert." : simulation.error.message; await deps.repository.recordFailure(audit.id, message); return err({ code: "keeperhub_failed", message }); }
  audit = await deps.repository.recordSimulation(audit.id, simulation.value);
  const submitted = await deps.keeperHub.execute(input.request); if (!submitted.ok) { await deps.repository.recordFailure(audit.id, submitted.error.message); return err({ code: "keeperhub_failed", message: submitted.error.message }); }
  audit = await deps.repository.recordSubmission(audit.id, submitted.value.executionId);
  const terminal = await deps.keeperHub.status(submitted.value.executionId); if (!terminal.ok || terminal.value.status !== "completed") { const message = terminal.ok ? `KeeperHub execution ended as ${terminal.value.status}.` : terminal.error.message; await deps.repository.recordFailure(audit.id, message); return err({ code: "keeperhub_failed", message }); }
  audit = await deps.repository.recordTerminal(audit.id, terminal.value); await deps.repository.addSpend({ agentId: input.agentId, executionId: audit.id, kind: "trade", amountUsdMicros: input.policyInput.notionalUsdMicros, utcDay: (input.now ?? new Date()).toISOString().slice(0, 10) }); return ok(audit);
} }; }
