import { and, eq } from "drizzle-orm";
import { cookies } from "next/headers";
import { NextResponse } from "next/server";
import { validateAgentSetup } from "../../../lib/agent/setup.ts";
import { hashToken } from "../../../lib/auth/email.ts";
import { loadConfig, runtimeEnvironment } from "../../../lib/config.ts";
import { resolveSession } from "../../../lib/db/auth-repository.ts";
import { createDatabase } from "../../../lib/db/client.ts";
import { agents } from "../../../lib/db/schema.ts";
import { KEEPERHUB_TEST_CHAIN_IDS, isLegacyMainnetDefault } from "../../../lib/chains.ts";
import { createMemoryClient } from "../../../lib/memory/client.ts";
import { writeMemoryEvent } from "../../../lib/memory/event-writer.ts";
async function context(){const token=(await cookies()).get("auctor_session")?.value;if(!token)return null;const config=loadConfig(runtimeEnvironment());if(!config.database.url)return null;const database=createDatabase(config.database.url);const session=await resolveSession(database.db,hashToken(token));return session?{database,session,config}:null}
export async function GET(){if(process.env.AUCTOR_E2E_AUTH==="1")return NextResponse.json({id:"e2e-agent",name:"Atlas",riskProfile:"balanced",tradingStyle:"Research opportunities, protect capital, and execute only within my limits.",autonomyMode:"manual",budgetUsd:"10",dailyCapUsd:"5",perTradeCapUsd:"2",allowedChains:["11155111","84532"],allowedTokens:["ETH","USDC"],maxSlippageBps:100,emergencyStop:false,khWalletAddress:"0x1111111111111111111111111111111111111111",onboardingCompletedAt:new Date().toISOString()});const ctx=await context();if(!ctx)return NextResponse.json({error:"unauthorized"},{status:401});try{const rows=await ctx.database.db.select().from(agents).where(and(eq(agents.id,ctx.session.agentId),eq(agents.userId,ctx.session.userId))).limit(1);const agent=rows[0];if(agent&&isLegacyMainnetDefault(agent.allowedChains)){const upgraded=(await ctx.database.db.update(agents).set({allowedChains:[...KEEPERHUB_TEST_CHAIN_IDS]}).where(and(eq(agents.id,ctx.session.agentId),eq(agents.userId,ctx.session.userId))).returning())[0];return NextResponse.json(upgraded)}return NextResponse.json(agent)}finally{await ctx.database.close()}}
export async function PUT(request:Request){const ctx=await context();if(!ctx)return NextResponse.json({error:"unauthorized"},{status:401});try{const setup=validateAgentSetup(await request.json());const rows=await ctx.database.db.update(agents).set({name:setup.name,riskProfile:setup.riskProfile,tradingStyle:setup.tradingStyle,autonomyMode:setup.autonomyMode,approvalMode:setup.autonomyMode==="manual"?"approve":"autonomous",budgetUsd:String(setup.budgetUsd),dailyCapUsd:String(setup.dailyCapUsd),perTradeCapUsd:String(setup.perTradeCapUsd),allowedChains:[...setup.allowedChains],allowedTokens:[...setup.allowedTokens],maxSlippageBps:setup.maxSlippageBps,emergencyStop:setup.emergencyStop}).where(and(eq(agents.id,ctx.session.agentId),eq(agents.userId,ctx.session.userId))).returning();if(ctx.config.agent.memoryPassphrase)await writeMemoryEvent({memory:createMemoryClient({baseUrl:ctx.config.memory.url}),userId:ctx.session.userId,agentId:ctx.session.agentId,memoryKey:ctx.session.memoryKey,masterPassphrase:ctx.config.agent.memoryPassphrase,type:"policy_changed",source:"web",content:`Agent settings updated. Risk ${setup.riskProfile}; autonomy ${setup.autonomyMode}; mandate: ${setup.tradingStyle}`,metadata:{daily_cap_usd:setup.dailyCapUsd,per_trade_cap_usd:setup.perTradeCapUsd,emergency_stop:setup.emergencyStop,allowed_chains:setup.allowedChains.join(","),allowed_tokens:setup.allowedTokens.join(",")}});return NextResponse.json(rows[0])}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"invalid_setup"},{status:400})}finally{await ctx.database.close()}}
