import { and, desc, eq } from "drizzle-orm";
import type { PostgresJsDatabase } from "drizzle-orm/postgres-js";
import { executions } from "../db/schema.ts";
import * as schema from "../db/schema.ts";
import { buildAuditTimeline } from "../execution/audit.ts";
import type { AuditDataSource, AuditDetail, AuditListItem, AuditQuery, AuditStatus } from "./types.ts";

type Database=PostgresJsDatabase<typeof schema>;type Row=typeof executions.$inferSelect;
export function createDatabaseAuditSource(db:Database,agentId:string,agentName:string):AuditDataSource{return{async list(query){const rows=await db.select().from(executions).where(and(eq(executions.agentId,agentId),...(query.status?[eq(executions.status,query.status)]:[]),...(query.chainId?[eq(executions.chainId,query.chainId)]:[]))).orderBy(desc(executions.createdAt)).limit(100);const term=query.search?.toLowerCase();return{kind:"ready",value:rows.filter(row=>!term||[row.correlationId,row.khExecutionId,row.txHash].some(value=>value?.toLowerCase().includes(term))).map(toList)}} ,async get(id){const rows=await db.select().from(executions).where(and(eq(executions.id,id),eq(executions.agentId,agentId))).limit(1);return rows[0]?{kind:"ready",value:toDetail(rows[0],agentName)}:{kind:"not_found"}}}}
function toList(row:Row):AuditListItem{return{id:row.id,status:status(row.status),action:action(row.intent),chainId:row.chainId,chainLabel:chain(row.chainId),correlationId:row.correlationId,policyVerdict:row.policyVerdict==="allowed"?"allowed":"refused",createdAt:row.createdAt.toISOString(),...(row.khExecutionId?{keeperHubExecutionId:row.khExecutionId}:{}),...(row.txHash?{transactionHash:row.txHash}:{})}}
function toDetail(row:Row,agentName:string):AuditDetail{const item=toList(row);const audit={id:row.id,agentId:row.agentId,correlationId:row.correlationId,status:row.status as any,...(isVerdict(row.policyDetail)?{policyVerdict:row.policyDetail}:{}),...(isSimulation(row.simulation)?{simulation:row.simulation}:{}),...(row.khExecutionId?{keeperHubExecutionId:row.khExecutionId}:{}),...(row.txHash?{transactionHash:row.txHash}:{})};return{...item,agent:agentName,sponsored:typeof row.receipt==="object"&&row.receipt!==null&&"sponsored"in row.receipt&&row.receipt.sponsored===true,timeline:buildAuditTimeline(audit),evidence:{memory:row.recalledMemory??[],research:row.researchUsed??[],reasoning:row.reasoning,policy:row.policyDetail,simulation:row.simulation,receipt:row.receipt,notifications:row.notified}}}
function status(value:string):AuditStatus{return value==="confirmed"||value==="refused"||value==="failed"?value:"pending"}function chain(id:string){return id==="8453"?"Base":id==="1"?"Ethereum":`Chain ${id}`}function action(value:unknown){if(typeof value==="object"&&value!==null&&"action"in value&&typeof value.action==="object"&&value.action!==null&&"kind"in value.action)return value.action.kind==="call"?"Onchain contract action":"Onchain transfer";return"Agent decision"}function isVerdict(v:unknown):v is any{return typeof v==="object"&&v!==null&&"allowed"in v}function isSimulation(v:unknown):v is any{return typeof v==="object"&&v!==null&&"status"in v&&v.status==="simulated"}
